// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MiniProjetBibliotheque.Data;

#nullable disable

namespace MiniProjetBibliotheque.Migrations
{
    [DbContext(typeof(DbContextBibliotheque))]
    [Migration("20220826095142_CreateDbBibliotheque")]
    partial class CreateDbBibliotheque
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("MiniProjetBibliotheque.Models.Auteur", b =>
                {
                    b.Property<int>("AuteurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuteurId"), 1L, 1);

                    b.Property<string>("EmailAuteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomAuteur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrenomAuteur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TelephoneAuteur")
                        .HasColumnType("int");

                    b.HasKey("AuteurId");

                    b.ToTable("Auteurs");
                });

            modelBuilder.Entity("MiniProjetBibliotheque.Models.Domaine", b =>
                {
                    b.Property<int>("DomaineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DomaineId"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomDomaine")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DomaineId");

                    b.ToTable("Domaines");
                });

            modelBuilder.Entity("MiniProjetBibliotheque.Models.Emprunt", b =>
                {
                    b.Property<int>("EmpruntId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmpruntId"), 1L, 1);

                    b.Property<DateTime>("DateEmprunt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateRetour")
                        .HasColumnType("datetime2");

                    b.Property<int>("LecteurId")
                        .HasColumnType("int");

                    b.Property<int>("LivreId")
                        .HasColumnType("int");

                    b.HasKey("EmpruntId");

                    b.HasIndex("LecteurId");

                    b.HasIndex("LivreId");

                    b.ToTable("Emprunts");
                });

            modelBuilder.Entity("MiniProjetBibliotheque.Models.Lecteur", b =>
                {
                    b.Property<int>("LecteurId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LecteurId"), 1L, 1);

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailLecteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Mdp_Lecteur")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomLecteur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PrenomLecteur")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TelephoneLecteur")
                        .HasColumnType("int");

                    b.HasKey("LecteurId");

                    b.ToTable("Lecteurs");
                });

            modelBuilder.Entity("MiniProjetBibliotheque.Models.Livre", b =>
                {
                    b.Property<int>("LivreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LivreId"), 1L, 1);

                    b.Property<int>("AuteurId")
                        .HasColumnType("int");

                    b.Property<int>("DomaineId")
                        .HasColumnType("int");

                    b.Property<int>("NombrePages")
                        .HasColumnType("int");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LivreId");

                    b.HasIndex("AuteurId");

                    b.HasIndex("DomaineId");

                    b.ToTable("Livres");
                });

            modelBuilder.Entity("MiniProjetBibliotheque.Models.Emprunt", b =>
                {
                    b.HasOne("MiniProjetBibliotheque.Models.Lecteur", "Lecteur")
                        .WithMany("EmpruntsLecteur")
                        .HasForeignKey("LecteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniProjetBibliotheque.Models.Livre", "Livre")
                        .WithMany("EmpruntsLivre")
                        .HasForeignKey("LivreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lecteur");

                    b.Navigation("Livre");
                });

            modelBuilder.Entity("MiniProjetBibliotheque.Models.Livre", b =>
                {
                    b.HasOne("MiniProjetBibliotheque.Models.Auteur", "Auteur")
                        .WithMany("LivresAuteur")
                        .HasForeignKey("AuteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiniProjetBibliotheque.Models.Domaine", "Domaine")
                        .WithMany("LivresDomaine")
                        .HasForeignKey("DomaineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Domaine");
                });

            modelBuilder.Entity("MiniProjetBibliotheque.Models.Auteur", b =>
                {
                    b.Navigation("LivresAuteur");
                });

            modelBuilder.Entity("MiniProjetBibliotheque.Models.Domaine", b =>
                {
                    b.Navigation("LivresDomaine");
                });

            modelBuilder.Entity("MiniProjetBibliotheque.Models.Lecteur", b =>
                {
                    b.Navigation("EmpruntsLecteur");
                });

            modelBuilder.Entity("MiniProjetBibliotheque.Models.Livre", b =>
                {
                    b.Navigation("EmpruntsLivre");
                });
#pragma warning restore 612, 618
        }
    }
}
